class StaticContent {
  static const String privacyPolicy = ''' 
<div class="privacy-policy">
                    <p><strong>1</strong>. <strong>Introduction</strong></p><p> Welcome to QatJobs. This Privacy Policy outlines the types of information we collect, how we use it, and the steps we take to protect your personal information.</p><p><br></p><p><strong>2. Information We Collect</strong></p><ul><li>Personal identification information (Name, email address, phone number, etc.).</li><li>Browser and visitation information.</li><li>Job application details.</li></ul><p><br></p><p><strong>3. How We Use Your Information</strong></p><p> We use the information we collect to:</p><ul><li>Provide and manage our services.</li><li>Process job applications.</li><li>Respond to user inquiries and offer support.</li><li>Improve our platform.</li></ul><p><br></p><p><strong>4. Protecting Your Data</strong></p><p> We employ data encryption and advanced security measures to ensure the safety of your personal information.</p><p><br></p><p><strong>5. Third-Party Sharing</strong></p><p> We do not sell or share your data with third-party entities unless required for service provision or by law.</p><p><br></p><p><strong>6.</strong> <strong>Cookie Policy</strong></p><p> Our website uses cookies to enhance user experience. By using our site, you agree to our use of cookies.</p><p><br></p><p><strong>7.</strong> <strong>Changes to This Policy</strong></p><p> We reserve the right to update our Privacy Policy. All changes will be notified on our platform.</p><p><br></p><p><strong>8. Contact Us</strong></p><p> For any concerns related to privacy, please contact us at [<a href="mailto:email@email.com" rel="\noopener" noreferrer="" target="_blank" style="color:" windowtext;="">contact@myqatarjobs.com</a>].</p>
                </div>
  ''';
  static const String termAndCondition = ''' 
  <div class="terms-desc">
                <p><strong>1. Introduction</strong></p><p> By using QatJobs, you agree to the following terms and conditions.</p><p><br></p><p><strong>2. Service Usage</strong></p><p> Users must:</p><ul><li>Provide accurate information during registration.</li><li>Not misuse or engage in illegal activities on our platform.</li></ul><p><br></p><p><strong>3. Content</strong></p><p> Job listings, resumes, and other content uploaded must be accurate and not violate any copyright or intellectual property rights.</p><p><br></p><p><strong>4. Termination</strong></p><p> We reserve the right to terminate accounts that violate our terms or engage in malicious activities.</p><p><br></p><p><strong>5. Limitation of Liability</strong></p><p> QatJobs is not responsible for hiring decisions, job listings, or disputes between employers and candidates.</p><p><br></p><p><strong>6. Governing Law</strong></p><p> These terms are governed by the laws of Qatar.</p><p><br></p><p><strong>7. Changes to These Terms</strong></p><p> QatJobs reserves the right to modify these terms. Users will be notified of any changes.</p><p><br></p><p><strong>8. Contact Us</strong></p><p> For any concerns or inquiries, please contact us at [<a href="mailto:email@email.com" rel="\noopener" noreferrer="" target="_blank" style="color:" windowtext;="">contact@myqatarjobs.com</a>].</p>
            </div>
  ''';
}
